<a href="https://colab.research.google.com/drive/1rGuL4bDUNdgzBHAEUJHZhVEnesRG7Hy8?usp=sharing">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

**Author Of the Notebook : Susnato Dhar (Github Link : https://github.com/susnato)**


This Notebook is a converted from PyTorch to JAX compatible from this original notebook <a href="https://github.com/probml/probml-notebooks/blob/main/notebooks/layer_norm_torch.ipynb">here</a>.

In [1]:
!pip install flax -q

     |████████████████████████████████| 184 kB 32.5 MB/s 
     |████████████████████████████████| 136 kB 47.2 MB/s 
     |████████████████████████████████| 70 kB 8.4 MB/s 


In [2]:
import jax
import jax.numpy as jnp
import jax.random as jrand
from flax import linen as nn

In [3]:
key = jrand.PRNGKey(42)

In [4]:
# batch size 3, feature size 2
X = jnp.array([[1, 2, 3], [4, 5, 6]])

print('batch norm')
mu_batch = jnp.mean(X,axis=0)
sigma_batch = jnp.std(X,axis=0)
XBN = (X-mu_batch)/sigma_batch
print(XBN)

print('layer norm')
mu_layer = jnp.expand_dims(jnp.mean(X,axis=1),axis=1)
sigma_layer = jnp.expand_dims(jnp.std(X,axis=1), axis=1)
XLN = (X-mu_layer)/sigma_layer
print(XLN)

batch norm
[[-1. -1. -1.]
 [ 1.  1.  1.]]
layer norm
[[-1.2247448  0.         1.2247448]
 [-1.2247448  0.         1.2247448]]


In [5]:
from flax import linen as nn

N, D = X.shape

ln = nn.LayerNorm()
bn = nn.BatchNorm(use_running_average=False, momentum=0.1, epsilon=1e-5,)

print('batch norm')
bn_vars = bn.init(key, X)
XBN_t, mutated_vars = bn.apply(bn_vars, X, mutable=['batch_stats'])
print(XBN_t)
assert(jnp.allclose(XBN_t, XBN, atol=1e-3))

print('layer norm')
ln_vars = ln.init(key, X)
XLN_t = ln.apply(ln_vars, X)
print(XLN_t)
assert(jnp.allclose(XLN_t, XLN, atol=1e-3))


batch norm
[[-0.9999978 -0.9999978 -0.9999978]
 [ 0.9999978  0.9999978  0.9999978]]
layer norm
[[-1.2247437  0.         1.2247437]
 [-1.2247428  0.         1.2247428]]
